galaxy_info:
  author: Jai Hirani
  description: User management for automation project
  company: Humber College
  min_ansible_version: 2.9
  platforms:
  - name: Ubuntu
    versions:
    - focal
dependencies: []
